sudo: false
language: c

os:
  - linux
  #- osx

compiler:
  #- clang
  - gcc
  
script:
 # download and compile ViennaRNA dependency
 #- wget https://depot.galaxyproject.org/software/vienna_rna/vienna_rna_1.8_src_all.tar.gz
 #- tar xvfz vienna_rna_1.8_src_all.tar.gz
 #- cd ViennaRNA-1.8.5 && ./configure --prefix=$HOME/vienna --without-perl && make && make install
 - make
 - ./align -h
 - perl marna.pl -h
